stages:
  - test
  - build
  - deploy

before_script:
  - echo "Recriando o arquivo .env a partir das variáveis do GitLab..."
  - rm -f .env
  - touch .env
  - echo "FIREBASE_CREDENTIALS_PATH=$FIREBASE_CREDENTIALS_PATH" >> .env
  - echo "DB_USER=$DB_USER" >> .env
  - echo "DB_PASSWORD=$DB_PASSWORD" >> .env
  - echo "DB_NAME=$DB_NAME" >> .env
  - echo "DATABASE_URL=$DATABASE_URL" >> .env
  - echo "DB_PORT_EXTERNAL=$DB_PORT_EXTERNAL" >> .env
  - echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> .env
  - echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> .env
  - echo "AWS_S3_BUCKET_NAME=$AWS_S3_BUCKET_NAME" >> .env
  - echo "AWS_REGION=$AWS_REGION" >> .env
  - echo "GF_ADMIN_USER=$GF_ADMIN_USER" >> .env
  - echo "GF_ADMIN_PASSWORD=$GF_ADMIN_PASSWORD" >> .env
  - echo "MAPBOX_API_KEY=$MAPBOX_API_KEY" >> .env
  - touch firebase_service_account.json
  - echo "$FIREBASE_JSON_CONTENT" > ./firebase_service_account.json
  
run_tests:
  stage: test
  tags:
    - vango-ec2
  script:
    - docker compose down --volumes --remove-orphans || true
    - docker compose up -d db
    - docker compose run --rm api pytest -p no:cacheprovider -q
  after_script:
    - docker compose down --volumes --remove-orphans

build_prod_image:
  stage: build
  tags:
    - vango-ec2
  script:
    - docker build -f Dockerfile.prod -t vango-api:$CI_COMMIT_SHA -t vango-api:latest .
  only:
    - main

deploy_to_ec2:
  stage: deploy
  tags:
    - vango-ec2
  script:
    - export IMAGE_TAG=$CI_COMMIT_SHA
    - export SNAPSHOT_ID="vango-db-prod-snapshot-$(date +%Y-%m-%d-%H-%M-%S)"
    - echo "Criando snapshot de segurança do RDS ($SNAPSHOT_ID)..."
    - aws rds create-db-snapshot --db-instance-identifier vango-db-production --db-snapshot-identifier $SNAPSHOT_ID --region $AWS_REGION
    - echo "Aguardando a conclusão do snapshot na AWS..."
    - aws rds wait db-snapshot-completed --db-snapshot-identifier $SNAPSHOT_ID --region $AWS_REGION
    - docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --wait api
    - docker compose -f docker-compose.yml -f docker-compose.prod.yml exec -T api alembic upgrade head
  only:
    - main
