"""fixes_migracoes_sprint1

Revision ID: 2670cdd23af9
Revises: f75ef777e5ab
Create Date: 2026-03-28 19:09:48.260744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2670cdd23af9'
down_revision: Union[str, Sequence[str], None] = 'f75ef777e5ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('addresses', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('dependents', sa.Column('guardian_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'dependents', 'users', ['guardian_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('routes_driver_id_fkey'), 'routes', type_='foreignkey')
    op.create_foreign_key(None, 'routes', 'users', ['driver_id'], ['id'], ondelete='CASCADE')
    op.alter_column('vehicles', 'driver_id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using='driver_id::uuid')
    op.alter_column('vehicles', 'status',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_constraint(op.f('vehicles_driver_id_key'), 'vehicles', type_='unique')
    op.create_foreign_key(None, 'vehicles', 'users', ['driver_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.create_unique_constraint(op.f('vehicles_driver_id_key'), 'vehicles', ['driver_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('vehicles', 'status',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('vehicles', 'driver_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               postgresql_using='driver_id::text')
    op.drop_constraint(None, 'routes', type_='foreignkey')
    op.create_foreign_key(op.f('routes_driver_id_fkey'), 'routes', 'users', ['driver_id'], ['id'])
    op.drop_constraint(None, 'dependents', type_='foreignkey')
    op.drop_column('dependents', 'guardian_id')
    op.alter_column('addresses', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
