"""setup tdd sprint 2

Revision ID: 3e3181478f8f
Revises: 7bd8d3d9cf81
Create Date: 2026-04-22 21:18:10.822623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e3181478f8f'
down_revision: Union[str, Sequence[str], None] = '7bd8d3d9cf81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route_passangers', sa.Column('pickup_address_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'route_passangers', 'addresses', ['pickup_address_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'route_passangers', type_='foreignkey')
    op.drop_column('route_passangers', 'pickup_address_id')
    # ### end Alembic commands ###
