"""fixes sprint 3

Revision ID: a8f8232b8f82
Revises: 0794342d139c
Create Date: 2026-05-11 20:58:28.848847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8f8232b8f82'
down_revision: Union[str, Sequence[str], None] = '0794342d139c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('push_token', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'push_token')
    # ### end Alembic commands ###
