name: Mirror to GitLab VanGO

on:
  push:
    branches:
      - main

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push to vango-api GitLab
        run: |
          git remote remove gitlab || true
          
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@tools.ages.pucrs.br/vango/vango-api.git
          
          git fetch origin main
          git checkout main
          git reset --hard origin/main
          
          git push gitlab main --force
